import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/common/header'
import Footer from '../components/Footer/Footer'
import Question from '../sections/Question/Question'
import AmazingProjects from '../sections/AmazingProjects/AmazingProjects'
import FeaturedClients from '../sections/FeaturedClients/FeaturedClients'
import SoftwareServices from '../sections/SoftwareServices/SoftwareServices'
import FooterForm from '../sections/FooterForm/FooterForm'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Apptimumlabs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Question />
      <AmazingProjects />
      <FeaturedClients />
      <SoftwareServices />
      <FooterForm/>
      <Footer />
    </>
  )
}
