import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/common/header'
import Footer from '../components/Footer/Footer'
import Question from '../sections/Question/Question'
import AmazingProjects from '../sections/AmazingProjects/AmazingProjects'
import FeaturedClients from '../sections/FeaturedClients/FeaturedClients'
import SoftwareServices from '../sections/SoftwareServices/SoftwareServices'
import FooterForm from '../sections/FooterForm/FooterForm'
import { Swiper, SwiperSlide } from "swiper/react";
import { Mousewheel, Pagination } from "swiper";
import "swiper/css";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";


// import required modules
// import { Mousewheel, Pagination } from "swiper";



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Apptimumlabs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Swiper
      direction={"vertical"}
        // loop={true}
        modules={[Mousewheel, Pagination]}
                mousewheel={true}

        slidesPerView={1}
        // autoplay={{
        //   delay: 2500,
        //   disableOnInteraction: false,
        // }}
        className="mySwiper !w-auto"
      >
        <SwiperSlide>

          <Question />
        </SwiperSlide>
        <SwiperSlide>

          <AmazingProjects />
        </SwiperSlide>
        <SwiperSlide>

          <FeaturedClients />
        </SwiperSlide>
        <SwiperSlide>

          <SoftwareServices />
        </SwiperSlide>
        <SwiperSlide>

        <FooterForm />
        </SwiperSlide>
        <SwiperSlide>

      <Footer />
        </SwiperSlide>
      </Swiper>
    </>
  )
}
